# Generated by Django 5.2.5 on 2025-08-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_s_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='s_superuser',
            new_name='is_superuser',
        ),
    ]
